# Generated by Django 5.0.1 on 2024-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Administrator'), ('librarian', 'Librarian'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
